### PR TITLE
Fix #1 for SCT-2921 deleted narratives remain

### PR DESCRIPTION
**Pull request by eapearson**
This fix is oriented at improving the experience for using the "Delete" operation, available from the narrative detail tool menu (the gear icon), without changing the underlying behavior yet.

It improves the text in the delete dialog, adds a dialog after deletion to inform the user that it may take up to 30 seconds for the display to reflect the deletion, and adds error handling for the case in which the user attempts to delete the same narrative after the initial deletion.

There are a few minor fixes included as well:
- added a cursor pointer for the tool menu
- a few code fixes

It also changes the behavior of the New Narrative button. It now opens the new Narrative in a new window. It was driving me crazy, and Miriam requested this as well.

If this is intentional behavior, we can revert it, but it reflects the way the narrative operates when creating a new narrative, as well as the previous behavior of the dashboard. No-one ever complained about that behavior, but I can imagine the stomping over the dashboard, especially now that it is a narrative manager, would be frustrating.

Easy enough to revert if this is intentional and desired behavior.

This is the first of a multi-pronged effort to improve this behavior.

The promised "30 seconds" for the display to reflect the deletion (which will also apply to renaming, copying, etc.) is not yet implemented. Look for another PR later today!

### CODE REVIEW

**Comment by eapearson** [comment]
Let me see about using Prettier, I see the dings for that. I used to use it, but stopped when it started conflicting with .. something else in VSC. Now I just use support for eslint-based formatting.

**Comment by dakotablair** [comment]
> It also changes the behavior of the New Narrative button.

I would suggest omitting this change in behavior. Users may decide whether they want to open a link in a new window, and it is generally better for accessibility to leave it up to the browser to decide how to handle links instead of telling them how. That being said, I am not totally against this change, but I would like some others to chime in here as well regarding this issue to see if we can build some consensus about what is desired.

Also LGTM seems to have suddenly decided that this link is now external. I think we should appease it by either adding `rel="noopener noreferrer"` or silencing the alert in LGTM. We know this link is not actually external, so our course should be decided based on whether we care if the referrer is passed or not. If we care about the referrer then silence the alert, otherwise add the `rel` attribute.

**Comment by elishawc** [comment]
open as new tab, please!

**Review by dakotablair — APPROVED** [review]
Looks good!

**Pull request merged**
